# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-05 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='branch',
        ),
        migrations.AlterField(
            model_name='batch',
            name='group',
            field=models.CharField(max_length=10),
        ),
    ]
