# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0002_auto_20160305_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='gender',
            field=models.CharField(default='M', max_length=1),
            preserve_default=False,
        ),
    ]
