# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 06:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0006_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='assessment',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='att',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='mst1',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='mst2',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='marks',
            name='sports',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
