# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0007_auto_20160307_1153'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='roll_no',
            field=models.IntegerField(default=11301148),
            preserve_default=False,
        ),
    ]
