# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-11 14:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0010_auto_20160309_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='date',
            field=models.DateField(default=datetime.datetime(2016, 3, 11, 14, 41, 23, 128700, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendance',
            name='lec',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='attendance',
            name='p_a',
            field=models.BooleanField(default=True),
        ),
    ]
