# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0012_remove_attendance_lec'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marks',
            name='assessment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='att',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mst1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='marks',
            name='mst2',
            field=models.IntegerField(default=0),
        ),
    ]
