# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0013_auto_20160404_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='flag',
            field=models.BooleanField(default=False),
        ),
    ]
