# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 08:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0014_marks_flag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject',
            new_name='subject_name',
        ),
    ]
