# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 09:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0015_auto_20160405_1356'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='subject_name',
            new_name='subject',
        ),
    ]
