# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0019_teacher_smb_passwd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('j_c', models.BooleanField(default=True)),
                ('j_c_name', models.CharField(max_length=50)),
                ('issn_isbn', models.CharField(max_length=15)),
                ('n_in', models.BooleanField(default=True)),
                ('authors', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rguide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('enroll', models.DateField()),
                ('degreeStudent', models.CharField(max_length=50)),
                ('sub_date', models.DateField()),
            ],
        ),
    ]
