# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-17 07:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0020_pubs_rguide'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pubs',
        ),
        migrations.DeleteModel(
            name='Rguide',
        ),
    ]
