# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-10-20 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acad', '0022_pubs_rguide'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pubs',
            name='j_c',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='pubs',
            name='n_in',
            field=models.CharField(max_length=15),
        ),
    ]
